//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XferSuite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int SEYR_Plot_Size {
            get {
                return ((int)(this["SEYR_Plot_Size"]));
            }
            set {
                this["SEYR_Plot_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9.75pt, style=Bold")]
        public global::System.Drawing.Font SEYR_Yield_Font {
            get {
                return ((global::System.Drawing.Font)(this["SEYR_Yield_Font"]));
            }
            set {
                this["SEYR_Yield_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 12pt")]
        public global::System.Drawing.Font SEYR_RC_Font {
            get {
                return ((global::System.Drawing.Font)(this["SEYR_RC_Font"]));
            }
            set {
                this["SEYR_RC_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SEYR_Show_Brackets {
            get {
                return ((bool)(this["SEYR_Show_Brackets"]));
            }
            set {
                this["SEYR_Show_Brackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SEYR_Flip_X {
            get {
                return ((bool)(this["SEYR_Flip_X"]));
            }
            set {
                this["SEYR_Flip_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SEYR_Flip_Y {
            get {
                return ((bool)(this["SEYR_Flip_Y"]));
            }
            set {
                this["SEYR_Flip_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SEYR_Delimeter {
            get {
                return ((int)(this["SEYR_Delimeter"]));
            }
            set {
                this["SEYR_Delimeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int SEYR_Num_Scroller_Images {
            get {
                return ((int)(this["SEYR_Num_Scroller_Images"]));
            }
            set {
                this["SEYR_Num_Scroller_Images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SEYR_Percentage_Sig_Figs {
            get {
                return ((int)(this["SEYR_Percentage_Sig_Figs"]));
            }
            set {
                this["SEYR_Percentage_Sig_Figs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int SEYR_Excel_Left_Start {
            get {
                return ((int)(this["SEYR_Excel_Left_Start"]));
            }
            set {
                this["SEYR_Excel_Left_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int SEYR_Excel_Top_Start {
            get {
                return ((int)(this["SEYR_Excel_Top_Start"]));
            }
            set {
                this["SEYR_Excel_Top_Start"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SEYR_Composite_X_Margin {
            get {
                return ((int)(this["SEYR_Composite_X_Margin"]));
            }
            set {
                this["SEYR_Composite_X_Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SEYR_Composite_Y_Margin {
            get {
                return ((int)(this["SEYR_Composite_Y_Margin"]));
            }
            set {
                this["SEYR_Composite_Y_Margin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public long SEYR_Large_File_Size {
            get {
                return ((long)(this["SEYR_Large_File_Size"]));
            }
            set {
                this["SEYR_Large_File_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SEYR_Show_PF_Data {
            get {
                return ((bool)(this["SEYR_Show_PF_Data"]));
            }
            set {
                this["SEYR_Show_PF_Data"] = value;
            }
        }
    }
}
