name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd ./XferSuite

      - name: Restore Packages
        run: nuget restore XferSuite.sln

      - name: Build Solution
        run: |
          msbuild.exe XferSuite.sln /p:platform="Any CPU" /p:configuration="Release"
